apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-statefulset
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  serviceName: {{ .Chart.Name }}-svc
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        resources:
          requests: {{ toYaml .Values.resources.requests | nindent 12 }}
          limits: {{ toYaml .Values.resources.limits | nindent 12 }}
        env:
        {{- range $key, $value := .Values.secrets }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.affinity.key }}
                operator: In
                values: {{ .Values.affinity.values | toJson }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.persistence.storage }}
